export default {
  homeList: [
    {
      id: "02",
      date: "2021年1月",
      imgUrl: "@/assets/images/home/home_list_img.png",
      titile : "调查与区划评估规范解读专题",
      zzdw: "国务院普查办",
      kcsl: "31讲",
      hdlx: "线上",
      pxdx: "全国省市县普查管理和技术支撑单位核心人员",
      pxrs: "1000余人",
      kscd: "17小时45分钟",
      ts: "4",
      kssj: "2020-01-15",
      jssj: "2020-01-27",
      hdjj: `根据普查全国试点任务特点及阶段工作安排，2021年1月，国务院普查办组织自然资源（地质、海洋）、住房和城乡建设部、交通运输部、水利部、应急部、气象局、林草局、地震局等普查主要参与部门和单位共计20余名技术专家，录制了普查业务培训第一批线上课程31课时，重点解读最新修订的调查类技术规范及相关调查软件系统操作。`,
      kcList: [
        {
          id: "201",
          name: "政府减灾能力调查技术规范",
          pepor: "徐  伟",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/jc/1.mp4",
          img: "@/assets/images/home/kcimg/img1.png",
          nr: `徐  伟 北京师范大学教授`,
          pid:'026',
          zwzc: "教授",
          kscd: "18分钟",
          fjid: "303acc00-029f-442c-9845-927434417230",
        },
        {
          id: "202",
          name: "乡镇与社区减灾能力调查技术规范",
          pepor: "徐  伟",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/jc/2.mp4",
          img: "@/assets/images/home/kcimg/img2.png",
          nr: `徐  伟 北京师范大学教授`,
          pid:'026',
          zwzc: "教授",
          kscd: "10分钟",
          fjid: "630c7712-16b9-40b4-afd9-61d4bc142095",
        },
        {
          id: "203",
          name: "企业与社会力量减灾能力调查",
          pepor: "张国明",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/jc/3.mp4",
          img: "@/assets/images/home/kcimg/img3.png",
          nr: `张国明 北京师范大学高工`,
          pid:'026',
          zwzc: "高工",
          kscd: "14分钟",
          fjid: "ec8a4950-4be8-4496-aa75-29c145eb199d",
        },
        {
          id: "204",
          name: "煤矿自然灾害承灾体调查与评估",
          pepor: "刘文岗",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/zd/1.mp4",
          img: "@/assets/images/home/kcimg/img4.png",
          nr: `刘文岗 煤炭科学研究总院研究员`,
          pid:'031',
          zwzc: "研究员",
          kscd: "49分钟",
          fjid: "34d303c2-b66d-4765-8bde-db145d6d9cec",
        },
        {
          id: "205",
          name: "危险化学品自然灾害承灾体调查培训",
          pepor: "马大庆",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/zd/2.mp4",
          img: "@/assets/images/home/kcimg/img5.png",
          nr: `马大庆 中国安科院工程师`,
          pid:'031',
          zwzc: "工程师",
          kscd: "30分钟",
          fjid: "25c756d4-ae03-4425-bdaa-45833e7313ab",
        },
        {
          id: "206",
          name: "公共服务设施调查任务、对象及技术流程",
          pepor: "张  化",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/jc/4.mp4",
          img: "@/assets/images/home/kcimg/026-张化1.png",
          nr: `张  化 北京师范大学高工`,
          pid:'026',
          zwzc: "高工",
          kscd: "36分钟",
          fjid: "ee654fef-f807-400c-8418-2b86ff31ccc8",
        },
        {
          id: "207",
          name: "公共服务设施调查案例和注意事项",
          pepor: "张  化",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/jc/5.mp4",
          img: "@/assets/images/home/kcimg/026-张化2.png",
          nr: `张  化 北京师范大学高工`,
          pid:'026',
          zwzc: "高工",
          kscd: "23分钟",
          fjid: "2a58cdb1-5a06-4568-8145-c259ed5e7f7c",
        },
        {
          id: "208",
          name: "自然灾害次生非煤矿山隐患调查技术规范",
          pepor: "李全明",
          url: "https://fxpc.mem.gov.cn/study/video/0128/8.mp4",
          img: "@/assets/images/home/kcimg/img8.png",
          nr: `李全明 中国安科院教授级高工`,
          pid:'031',
          zwzc: "教授级高工",
          kscd: "47分钟",
          fjid: "3a1a815c-fd79-4af5-8b1c-1b79f5acfacb",
        },
        {
          id: "209",
          name: "农村房屋建筑调查",
          pepor: "朱立新",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/zj/2.mp4",
          img: "@/assets/images/home/kcimg/img9.png",
          nr: `朱立新 中国建筑科学研究院有限公司研究员`,
          pid:'023',
          zwzc: "研究员",
          kscd: "47分钟",
          fjid: "a2e223e2-8d23-4727-86e4-422129bcbb35",
        },
        {
          id: "210",
          name: "历史灾害调查技术规范",
          pepor: "张云霞",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/ls/5.mp4",
          img: "@/assets/images/home/kcimg/img10.png",
          nr: `张云霞 国家减灾中心研究员`,
          pid:'027',
          zwzc: "研究员",
          kscd: "54分钟",
          fjid: "fe93e1c6-b0c8-4dd9-8a3c-840b6442d4c1",
        },
        {
          id: "211",
          name: "气象灾害综合风险普查总体技术方案",
          pepor: "王国复",
          url: "https://fxpc.mem.gov.cn/study/video/0204/11.mp4",
          img: "@/assets/images/home/kcimg/028-王国复.png",
          nr: `王国复 国家气候中心研究员`,
          pid:'028',
          zwzc: "研究员",
          kscd: "43分钟",
          fjid: "f5b269b3-fb64-48cb-b0ff-5dc35f4bede8",
        },
        {
          id: "212",
          name: "地质灾害风险调查评价技术规范",
          pepor: "房  浩",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/dz/1.mp4",
          img: "@/assets/images/home/kcimg/022-房浩.png",
          nr: `房  浩 中国地质调查局水环部教授级高工`,
          pid:'022',
          zwzc: "房 浩 中国地质调查局水环部教授级高工",
          kscd: "45分钟",
          fjid: "d6ff798a-ca9f-40a7-a387-24a6245075d2",
        },
        {
          id: "213",
          name: "场地地震工程地质条件勘察与资料收集",
          pepor: "吴  昊",
          url: "https://fxpc.mem.gov.cn/study/video/0128/13.mp4",
          img: "@/assets/images/home/kcimg/img13.png",
          nr: `吴  昊 中国地震灾害防御中心高工`,
          pid:'021',
          zwzc: "高工",
          kscd: "42分钟",
          fjid: "b1475724-724d-4517-bd45-6393e8fca54a",
        },
        {
          id: "214",
          name: "致死性实地调查技术",
          pepor: "夏朝旭",
          url: "https://fxpc.mem.gov.cn/study/video/0204/14.mp4",
          img: "@/assets/images/home/kcimg/021-夏朝旭.png",
          nr: `夏朝旭 中国地震局地质研究所副研究员`,
          pid:'021',
          zwzc: "副研究员",
          kscd: "47分钟",
          fjid: "d7c43ffc-fd88-488e-9131-83fdd041ca6c",
        },
        {
          id: "215",
          name: "森林草原火灾调查与风险评估总体方案",
          pepor: "杨雪清",
          url: "https://fxpc.mem.gov.cn/study/video/0204/15.mp4",
          img: "@/assets/images/home/kcimg/029-杨雪清1.png",
          nr: `杨雪清 国家林业和草原局调查规划设计院 教授级高工`,
          pid:'029',
          zwzc: "教授级高工",
          kscd: "38分钟",
          fjid: "a17afbdb-5ef8-4474-90c3-6f1819623237",
        },
        {
          id: "216",
          name: "可燃物标准地/大样地调查、野外火源调查、历史灾害调查",
          pepor: "杨雪清",
          url: "https://fxpc.mem.gov.cn/study/video/0204/16.mp4",
          img: "@/assets/images/home/kcimg/029-杨雪清2.png",
          nr: `杨雪清 国家林业和草原局调查规划设计院教授级高工`,
          pid:'029',
          zwzc: "教授级高工",
          kscd: "1小时6分钟",
          fjid: "68f13756-8a0f-4f73-b6fc-b95a30af9a8c",
        },
        {
          id: "21701",
          name: "市政设施承灾体普查技术要点",
          pepor: "王圣伟",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/zj/3.mp4",
          img: "@/assets/images/home/kcimg/img17_01.png",
          nr: `王圣伟 北京市市政工程设计研究总院有限公司教授级高工`,
          pid:'023',
          zwzc: "教授级高工",
          kscd: "73分钟",
          fjid: "de1df94f-c3ac-443c-a912-699039ccbd4f",
        },
        // {
        //   id: "21702",
        //   name: "市政设施承灾体调查_2",
        //   pepor: "王圣伟",
        //   url: "https://fxpc.mem.gov.cn/study/video/0128/17-02.mp4",
        //   img: "@/assets/images/home/kcimg/img17_02.png",
        //   nr: `王圣伟 北京市市政工程设计研究总院有限公司教授级高工`,
        //   pid:'023',
        //   zwzc: "教授级高工",
        //   kscd: "16分钟",
        //   fjid: "908b6e4a-0514-4357-bd52-8f12c59c5434",
        // },
        {
          id: "218",
          name: "全国城镇房屋建筑调查技术要点",
          pepor: "史铁花",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/zj/4.mp4",
          img: "@/assets/images/home/kcimg/img18.png",
          nr: `史铁花 中国建筑科学研究院有限公司研究员`,
          pid:'023',
          zwzc: "研究员",
          kscd: "43分钟",
          fjid: "b3291722-274f-4c58-84f9-83ba27cd7d30",
        },
        {
          id: "219",
          name: "软件系统和数据处理",
          pepor: "武彦清",
          url: "https://fxpc.mem.gov.cn/study/video/0128/19.mp4",
          img: "@/assets/images/home/kcimg/img19.png",
          nr: `武彦清 住房和城乡建设部信息中心高工`,
          pid:'023',
          zwzc: "高工",
          kscd: "44分钟",
          fjid: "65cdb538-7386-4014-9811-33747178c65f",
        },
        {
          id: "220",
          name: "水旱灾害风险普查任务内容与技术要求",
          pepor: "孙东亚",
          url: "https://fxpc.mem.gov.cn/study/video/0204/20.mp4",
          img: "@/assets/images/home/kcimg/030-孙东亚.png",
          nr: `孙东亚 水利部减灾中心正高`,
          pid:'030',
          zwzc: "正高",
          kscd: "1小时6分钟",
          fjid: "646816be-f266-478a-9df5-a65e06aaba9c",
        },
        {
          id: "221",
          name: "全国海洋灾害风险普查实施方案解读",
          pepor: "刘  强",
          url: "https://fxpc.mem.gov.cn/study/video/0204/21.mp4",
          img: "@/assets/images/home/kcimg/025-刘强.png",
          nr: `刘  强 自然资源部海洋减灾中心处长/高工`,
          pid:'025',
          zwzc: "处长/高工",
          kscd: "32分钟",
          fjid: "c9843fab-4eaf-4ed1-b531-476b02b30404",
        },
        {
          id: "222",
          name: "海洋灾害致灾调查、重点隐患调查评估",
          pepor: "张  尧",
          url: "https://fxpc.mem.gov.cn/study/video/0204/22.mp4",
          img: "@/assets/images/home/kcimg/025-张尧.png",
          nr: `张  尧 自然资源部海洋减灾中心副研究员`,
          pid:'025',
          zwzc: "副研究员",
          kscd: "19分钟",
          fjid: "968305b5-77f0-4dd7-8ca3-ea6a3ce4ea67",
        },
        {
          id: "223",
          name: "可燃物标准地/大样地调查、野外火源调查、历史灾害调查软件系统操作",
          pepor: "廖志杰",
          url: "https://fxpc.mem.gov.cn/study/video/0204/23.mp4",
          img: "@/assets/images/home/kcimg/029-廖志杰.png",
          nr: `廖志杰 国家林业和草原局调查规划设计院高级工程师`,
          pid:'029',
          zwzc: "高级工程师",
          kscd: "14分钟",
          fjid: "67e48114-4712-4486-89c6-9d6e59300431",
        },
        {
          id: "224",
          name: "自然灾害综合风险公路承灾体普查",
          pepor: "杨  峰",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/gl/1.mp4",
          img: "@/assets/images/home/kcimg/024-杨峰.png",
          nr: `杨 峰 交通运输部路网监测与应急处置中心处长`,
          pid:'024',
          zwzc: "处长",
          kscd: "26分钟",
          fjid: "77f63fe1-b01d-49f3-8885-ec43252ab202",
        },
        {
          id: "225",
          name: "公路灾害风险普查技术指南培训（数据采集、成果质检）",
          pepor: "夏旺民",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/gl/2.mp4",
          img: "",
          nr: `夏旺民 中交第一公路勘察设计研究院教授级高工`,
          pid:'024',
          zwzc: "教授级高工",
          kscd: "1小时15分钟",
          fjid: "402b38f8-ef39-4451-8bb4-ca1797fd7d90",
        },
        {
          id: "226",
          name: "自然灾害综合风险公路承灾体采集系统",
          pepor: "刘  悦",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/gl/3.mp4",
          img: "@/assets/images/home/kcimg/024-刘悦.png",
          nr: `刘 悦 交通运输部路网监测与应急处置中心高工`,
          pid:'024',
          zwzc: "高工",
          kscd: "32分钟",
          fjid: "14ebf570-1282-41d9-bfd9-b38d2c57fa0f",
        },
        {
          id: "227",
          name: "公路承灾体普查数据核查讲解",
          pepor: "陈  昕",
          url: "https://fxpc.mem.gov.cn/study/video/0204/27.mp4",
          img: "@/assets/images/home/kcimg/024-陈昕.png",
          nr: `陈  昕 中国交通通信信息中心教授级高工`,
          pid:'024',
          zwzc: "高工",
          kscd: "32分钟",
          fjid: "0e63dd36-6f8f-465a-9f7c-82cf35aa9cc9",
        },
        {
          id: "228",
          name: "自然灾害综合风险水路承灾体普查技术指南解读",
          pepor: "寇本川",
          url: "https://fxpc.mem.gov.cn/study/video/0204/28.mp4",
          img: "@/assets/images/home/kcimg/024-寇本川.png",
          nr: `寇本川 中交水运规划设计院高级工程师`,
          pid:'024',
          zwzc: "高级工程师",
          kscd: "38分钟",
          fjid: "82007468-1263-4523-ad6b-2c710a56571f",
        },
        {
          id: "229",
          name: "水路承灾体普查系统操作讲解",
          pepor: "孙  林",
          url: "https://fxpc.mem.gov.cn/study/video/0204/29.mp4",
          img: "@/assets/images/home/kcimg/024-孙林.png",
          nr: `孙  林 中交水运规划设计院工程师`,
          pid:'024',
          zwzc: "工程师",
          kscd: "14分钟",
          fjid: "61c692a4-66dc-418e-89d9-8440a1fa01d4",
        },{
          id: "230",
          name: "民用核设施自然灾害重点隐患排查数据采集与核查",
          pepor: "潘 蓉",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/my/1.mp4",
          img: "@/assets/images/home/kcimg/032-潘蓉.png",
          nr: `潘 蓉 生态环境部核与辐射安全中心处长/研究员`,
          pid:'032',
          zwzc: "处长/研究员",
          kscd: "53分钟",
          fjid: "d071940d-5af2-495c-b146-e6ad62ff8e9d",
        },
        {
          id: "231",
          name: "非煤矿山自然灾害承灾体调查与评估",
          pepor: "张 红",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/zd/3.mp4",
          img: "",
          nr: `张 红`,
          pid:'031',
          zwzc: "",
          kscd: "43分钟",
          fjid: "",
        },
        {
          id: "232",
          name: "县级1：5万活动断层分布图",
          pepor: "石 峰",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/zd/4.mp4",
          img: "",
          nr: `石 峰`,
          pid:'031',
          zwzc: "",
          kscd: "29分钟",
          fjid: "",
        },
        {
          id: "233",
          name: "海平面上升风险评估与区划",
          pepor: "董军兴",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/hy/1.mp4",
          img: "",
          nr: `董军兴`,
          pid:'025',
          zwzc: "",
          kscd: "16分钟",
          fjid: "",
        },
        {
          id: "234",
          name: "海浪灾害风险评估教材讲座",
          pepor: "侯 放",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/hy/2.mp4",
          img: "",
          nr: `侯 放`,
          pid:'025',
          zwzc: "",
          kscd: "16分钟",
          fjid: "",
        },
        {
          id: "235",
          name: "海啸灾害风险评估与区划",
          pepor: "侯京明",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/hy/3.mp4",
          img: "",
          nr: `侯京明`,
          pid:'025',
          zwzc: "",
          kscd: "17分钟",
          fjid: "",
        },
        {
          id: "236",
          name: "海冰灾害风险评估与区划",
          pepor: "黎 舸",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/hy/4.mp4",
          img: "",
          nr: `黎 舸`,
          pid:'025',
          zwzc: "",
          kscd: "13分钟",
          fjid: "",
        },
        {
          id: "237",
          name: "风暴潮灾害风险评估和区划",
          pepor: "石先武",
          url: "https://fxpc.mem.gov.cn/study/video/pcqh/hy/5.mp4",
          img: "",
          nr: `石先武`,
          pid:'025',
          zwzc: "",
          kscd: "24分钟",
          fjid: "",
        },
      ]
    },
    {
      id: "01",
      date: "2020年12月",
      imgUrl: "@/assets/images/home/home_list_img.png",
      titile: "组织统筹与技术统筹专题",
      zzdw: "国务院普查办",
      kcsl: "25讲",
      hdlx: "线下",
      pxdx: "全国省级普查办和技术支撑单位骨干",
      pxrs: "160余人",
      kscd: "12小时46分钟",
      ts: "4",
      kssj: "2020-12-20",
      jssj: "2020-12-24",
      hdjj:
        "由国务院普查办主办的第一次全国自然灾害综合风险普查业务培训班于2020 年 12 月 20 日至 24 日在华北科技学院兴安苑交流中心进行，培训内容包括试点“大会战”经验介绍及地方试点工作经验交流、调查工作专题讲解、评估区划专题介绍、普查办工作专题介绍、数据管理工作专题、软件系统建设工作专题介绍",
      kcList: [
        {
          id: "1",
          name: "北京市第一次全国自然灾害综合风险普查房山试点工作交流",
          pepor: "封光",
          url: "https://fxpc.mem.gov.cn/study/video/12.21am/1.mp4",
          img: "@/assets/images/activity/kc1.png",
          nr: `封 光 北京市应急管理局监测减灾处`,
          pid: "1",
          zwzc: "",
          kscd: "1小时26分钟",
          fjid: "d36579bc-6942-47da-9009-5d40840bea8a"
        },
        {
          id: "2",
          name: "山东省第一次全国自然灾害综合风险普查岚山试点工作交流",
          pepor: "汤桂勇",
          url: "https://fxpc.mem.gov.cn/study/video/12.21am/2.mp4",
          img: "@/assets/images/activity/kc2.png",
          nr: `汤桂勇 日照市岚山区普查工作专班`,
          pid: "1",
          zwzc: "",
          kscd: "1小时9分钟",
          fjid: "6696ce74-c441-477f-a8c3-cb2804eeaa14"
        },
        {
          id: "3",
          name: "浙江省普查工作情况汇报",
          pepor: "石永国",
          url: "https://fxpc.mem.gov.cn/study/video/12.21pm/1.mp4",
          img: "@/assets/images/activity/kc3.png",
          nr: `石永国 浙江省普查办`,
          pid: "1",
          zwzc: "",
          kscd: "37分钟",
          fjid: "a50f0f95-7869-4d32-ab2f-958cbefdebde"
        },
        {
          id: "4",
          name: "江西省普查工作情况汇报",
          pepor: "陈勇",
          url: "https://fxpc.mem.gov.cn/study/video/12.21pm/2.mp4",
          img: "@/assets/images/activity/kc4.png",
          nr: `陈 勇 江西省普查办`,
          pid: "1",
          zwzc: "",
          kscd: "25分钟",
          fjid: "07e7dff6-1d8d-4f64-9578-bd8db7aa3536"
        },
        {
          id: "5",
          name: "河南省普查工作情况汇报",
          pepor: "陈学胜",
          url: "https://fxpc.mem.gov.cn/study/video/12.21pm/3.mp4",
          img: "@/assets/images/activity/kc5.png",
          nr: `陈学胜 河南省普查办`,
          pid: "1",
          zwzc: "",
          kscd: "13分钟",
          fjid: "2070d71e-9538-465f-aa42-36e9c1ec8247"
        },
        {
          id: "6",
          name: "广东省普查工作情况汇报",
          pepor: "刘鹏辉",
          url: "https://fxpc.mem.gov.cn/study/video/12.21pm/4.mp4",
          img: "@/assets/images/activity/kc6.png",
          nr: `刘鹏辉 广东省普查办`,
          pid: "1",
          zwzc: "",
          kscd: "17分钟",
          fjid: "ae693eb8-b16e-41a0-a716-77003d1dcae2"
        },
        {
          id: "7",
          name: "贵州省普查工作情况汇报",
          pepor: "叶红",
          url: "https://fxpc.mem.gov.cn/study/video/12.21pm/5.mp4",
          img: "@/assets/images/activity/kc7.png",
          nr: `叶 红 贵州省应急管理厅`,
          pid: "1",
          zwzc: "",
          kscd: "24分钟",
          fjid: "c449f4f1-6ad4-4547-b346-f2e702a96415"
        },
        {
          id: "8",
          name: "甘肃省普查工作情况汇报",
          pepor: "杨帆",
          url: "https://fxpc.mem.gov.cn/study/video/12.21pm/6.mp4",
          img: "@/assets/images/activity/kc8.png",
          nr: `杨 帆 甘肃省普查办`,
          pid: "1",
          zwzc: "",
          kscd: "20分钟",
          fjid: "ea8e01a0-6886-439a-9fd8-4ddd03dc49ee"
        },
        {
          id: "9",
          name: "普查调查总体任务",
          pepor: "赵飞",
          url: "https://fxpc.mem.gov.cn/study/video/12.22am/1.mp4",
          img: "@/assets/images/activity/kc9.png",
          nr: `赵 飞 国务院普查办调查组组长`,
          pid: "2",
          zwzc: "组长",
          kscd: "41分钟",
          fjid: "0eb30982-d458-442e-9642-9d2b0082bf91"
        },
        {
          id: "10",
          name: "调查技术规范最新修改情况",
          pepor: "王曦",
          url: "https://fxpc.mem.gov.cn/study/video/12.22am/2.mp4",
          img: "@/assets/images/activity/kc10.png",
          nr: `王 曦 国务院普查办调查组副组长`,
          pid: "2",
          zwzc: "副组长",
          kscd: "35分钟",
          fjid: "c8ed13d8-64fb-4a8d-95ea-64fdc11dface"
        },
        {
          id: "11",
          name: "普查采集系统介绍",
          pepor: "刘蓓蓓",
          url: "https://fxpc.mem.gov.cn/study/video/12.22am/3.mp4",
          img: "@/assets/images/activity/kc11.png",
          nr: `刘蓓蓓 国务院普查办调查组成员`,
          pid: "2",
          zwzc: "成员",
          kscd: "40分钟",
          fjid: "233bd8b6-0e4a-4d31-b039-498de567aaf2"
        },
        {
          id: "12",
          name: "综合评估总体技术方案",
          pepor: "汪明",
          url: "https://fxpc.mem.gov.cn/study/video/12.22pm/1.mp4",
          img: "@/assets/images/activity/kc12.png",
          nr: `汪 明 国务院普查办评估组组长`,
          pid: "3",
          zwzc: "组长",
          kscd: "31分钟",
          fjid: "bbd37344-a4e4-44ab-9529-e63679e605b1"
        },
        {
          id: "13",
          name: "自然灾害综合区划",
          pepor: "王瑛",
          url: "https://fxpc.mem.gov.cn/study/video/12.22pm/2.mp4",
          img: "@/assets/images/activity/kc13.png",
          nr: `王 瑛 国务院普查办评估组副组长`,
          pid: "3",
          zwzc: "副组长",
          kscd: "11分钟",
          fjid: "c3e72ae5-af5f-4098-9e11-1f2bea0211b8"
        },
        {
          id: "14",
          name: "综合减灾资源（能力）评估",
          pepor: "刘凯",
          url: "https://fxpc.mem.gov.cn/study/video/12.22pm/3.mp4",
          img: "@/assets/images/activity/kc14.png",
          nr: `刘 凯 国务院普查办评估组成员长`,
          pid: "3",
          zwzc: "成员长",
          kscd: "14分钟",
          fjid: "e28a9f5e-615d-446c-b916-0ba07e05f562"
        },
        {
          id: "15",
          name: "自然灾害综合风险评估",
          pepor: "杨赛霓",
          url: "https://fxpc.mem.gov.cn/study/video/12.22pm/4.mp4",
          img: "@/assets/images/activity/kc15.png",
          nr: `杨赛霓 国务院普查办评估组副组长`,
          pid: "3",
          zwzc: "副组长",
          kscd: "9分钟",
          fjid: "f140fe1a-0d2e-403f-a77a-6c3b807826ba"
        },
        {
          id: "17",
          name: "历史灾害调查评估技术规范",
          pepor: "张云霞",
          url: "https://fxpc.mem.gov.cn/study/video/12.22pm/6.mp4",
          img: "@/assets/images/activity/kc17.png",
          nr: `张云霞 国务院普查办评估组副组长`,
          pid: "3",
          zwzc: "副组长",
          kscd: "16分钟",
          fjid: "1e7abad4-4850-4f31-8eed-a2b7f46c3eec"
        },
        {
          id: "16",
          name: "自然灾害重点隐患综合评估",
          pepor: "方伟华",
          url: "https://fxpc.mem.gov.cn/study/video/12.22pm/5.mp4",
          img: "@/assets/images/activity/kc16.png",
          nr: `方伟华 国务院普查办评估组副组长`,
          pid: "3",
          zwzc: "副组长",
          kscd: "15分钟",
          fjid: "edac370b-c2c0-4476-a341-650b4d9c810f"
        },
        {
          id: "18",
          name: "数据与成果汇交和质量审核办法",
          pepor: "刘龙飞",
          url: "https://fxpc.mem.gov.cn/study/video/12.23am/1.mp4",
          img: "@/assets/images/activity/kc18.png",
          nr: `刘龙飞 国务院普查办数据与成果应用组副组长`,
          pid: "4",
          zwzc: "副组长",
          kscd: "41分钟",
          fjid: "b042f0b3-67da-4fe5-854c-6142168b407f"
        },
        {
          id: "19",
          name: "普查软件系统总体方案",
          pepor: "张学华",
          url: "https://fxpc.mem.gov.cn/study/video/12.23am/2.mp4",
          img: "@/assets/images/activity/kc19.png",
          nr: `张学华 国务院普查办软件与数据库组副组长`,
          pid: "5",
          zwzc: "副组长",
          kscd: "36分钟",
          fjid: "49acd69f-19e2-47dd-9270-5bf156ca2e1c"
        },
        {
          id: "20",
          name: "普查办主要职责与日常运转",
          pepor: "周洪建",
          url: "https://fxpc.mem.gov.cn/study/video/12.23am/3.mp4",
          img: "@/assets/images/activity/kc20.png",
          nr: `周洪建 国务院普查办综合组组长`,
          pid: "6",
          zwzc: "组长",
          kscd: "1小时8分钟",
          fjid: "182983b5-828a-4cfd-af8d-31cbd623c2a0"
        },
        {
          id: "21",
          name: "全国试点阶段宣传工作",
          pepor: "徐娜",
          url: "https://fxpc.mem.gov.cn/study/video/12.23pm/1.mp4",
          img: "@/assets/images/activity/kc21.png",
          nr: `徐 娜 国务院普查办综合组副组长`,
          pid: "6",
          zwzc: "副组长",
          kscd: "12分钟",
          fjid: "a523cfa6-95cf-4a26-bef2-00887e856ab8"
        },
        {
          id: "22",
          name: "调度管理系统介绍",
          pepor: "崔燕",
          url: "https://fxpc.mem.gov.cn/study/video/12.23pm/2.mp4",
          img: "@/assets/images/activity/kc22.png",
          nr: `崔 燕 国务院普查办软件系统与数据库组成员`,
          pid: "6",
          zwzc: "成员",
          kscd: "20分钟",
          fjid: "a93428c9-4048-4408-8a83-7985c7bf0a87"
        },
        {
          id: "23",
          name: "调度管理系统功能演示",
          pepor: "吴灿",
          url: "https://fxpc.mem.gov.cn/study/video/12.23pm/3.mp4",
          img: "@/assets/images/activity/kc23.png",
          nr: `吴 灿 国信司南(北京)地理信息技术有限公司`,
          pid: "6",
          zwzc: "",
          kscd: "21分钟",
          fjid: "e50c77a0-39c9-44a4-b013-c3940ea03daf"
        },
        {
          id: "24",
          name: "省级实施方案编制要求",
          pepor: "赵飞",
          url: "https://fxpc.mem.gov.cn/study/video/12.23pm/4.mp4",
          img: "@/assets/images/activity/kc24.png",
          nr: `赵 飞 国务院普查办调查组组长`,
          pid: "6",
          zwzc: "组长",
          kscd: "15分钟",
          fjid: "d0bb4ecb-a547-409f-afad-1473aa279727"
        },
        {
          id: "25",
          name: "培训总结",
          pepor: "袁艺",
          url: "https://fxpc.mem.gov.cn/study/video/12.23pm/5.mp4",
          img: "@/assets/images/activity/kc24.png",
          nr: `袁 艺 国务院普查领导小组办公室副主任`,
          pid: "7",
          zwzc: "副主任",
          kscd: "38分钟",
          fjid: "1537b35a-9723-4190-87d2-ea997141e8f6"
        }
      ]
    },
    {
      id: "03",
      date: "2021年03月",
      imgUrl: "@/assets/images/home/home_list_img.png",
      titile: "软件系统操作说明专题",
      zzdw: "国务院普查办",
      kcsl: "10讲",
      hdlx: "线上",
      pxdx: "全国省市县普查办、行业部门和技术支撑单位相关人员",
      pxrs: "1000",
      kscd: "27分钟",
      ts: "4",
      kssj: "2021-03-08",
      jssj: "2021-03-19",
      hdjj:
        "活动简介：随着第一次全国自然灾害综合风险普查相关软件系统的上线运行，同步制作了软件使用操作说明相关的课程，供相关用户查看，帮助用户快速掌握软件操作流程，推进相关的普查工作。",
      kcList: [
        {
          id: "1",
          name: "工作进展统计表的填报流程及进入系统步骤",
          pepor: "技术支持",
          url: "https://fxpc.mem.gov.cn/study/video/0308/1.mp4",
          img: "@/assets/images/activity/imgdd1.png",
          nr: `技术支持 国信司南(北京)地理信息技术有限公司，中级工程师`,
          pid: "031",
          zwzc: "",
          kscd: "2分钟",
          fjid: "bed185d0-f2c0-45ac-ba82-43434489b7bc"
        },{
          id: "2",
          name: "如何填报工作进展统计表",
          pepor: "技术支持",
          url: "https://fxpc.mem.gov.cn/study/video/0308/2.mp4",
          img: "@/assets/images/activity/imgdd2.png",
          nr: `技术支持 国信司南(北京)地理信息技术有限公司，中级工程师`,
          pid: "031",
          zwzc: "",
          kscd: "2分钟",
          fjid: "9fb46417-747f-4c9b-a9a2-7011ea7e36b2"
        },{
          id: "3",
          name: "试点工作统计表的填报流程及进入系统步骤",
          pepor: "技术支持",
          url: "https://fxpc.mem.gov.cn/study/video/0308/3.mp4",
          img: "@/assets/images/activity/imgdd3.png",
          nr: `技术支持 国信司南(北京)地理信息技术有限公司，中级工程师`,
          pid: "031",
          zwzc: "",
          kscd: "2分钟",
          fjid: "dbc9088c-bb03-42be-a532-597764d42045"
        },{
          id: "4",
          name: "如何填报试点工作统计表",
          pepor: "技术支持",
          url: "https://fxpc.mem.gov.cn/study/video/0308/4.mp4",
          img: "@/assets/images/activity/imgdd4.png",
          nr: `技术支持 国信司南(北京)地理信息技术有限公司，中级工程师`,
          pid: "031",
          zwzc: "",
          kscd: "4分钟",
          fjid: "f8d121f6-8199-4dc7-91c4-68d1d4215693"
        },{
          id: "5",
          name: "进入系统",
          pepor: "技术支持",
          url: "https://fxpc.mem.gov.cn/study/video/0308/5.mp4",
          img: "@/assets/images/activity/imgdd5.png",
          nr: `技术支持 国信司南(北京)地理信息技术有限公司，中级工程师`,
          pid: "032",
          zwzc: "",
          kscd: "2分钟",
          fjid: "00bae089-fb39-4bd9-9722-0e0b30500a71"
        },{
          id: "6",
          name: "村级代码调整",
          pepor: "技术支持",
          url: "https://fxpc.mem.gov.cn/study/video/0308/6.mp4",
          img: "@/assets/images/activity/imgdd6.png",
          nr: `技术支持 国信司南(北京)地理信息技术有限公司，中级工程师`,
          pid: "032",
          zwzc: "",
          kscd: "3分钟",
          fjid: "316b8d21-d1f0-4f54-a300-bfe16788c930"
        },{
          id: "7",
          name: "乡镇代码调整",
          pepor: "技术支持",
          url: "https://fxpc.mem.gov.cn/study/video/0308/7.mp4",
          img: "@/assets/images/activity/imgdd7.png",
          nr: `技术支持 国信司南(北京)地理信息技术有限公司，中级工程师`,
          pid: "032",
          zwzc: "",
          kscd: "4分钟",
          fjid: "3b801e7c-b100-4988-8182-615db926bbdd"
        },{
          id: "8",
          name: "行政驻地调整",
          pepor: "技术支持",
          url: "https://fxpc.mem.gov.cn/study/video/0308/8.mp4",
          img: "@/assets/images/activity/imgdd8.png",
          nr: `技术支持 国信司南(北京)地理信息技术有限公司，中级工程师`,
          pid: "032",
          zwzc: "",
          kscd: "2分钟",
          fjid: "87bd872b-083e-4452-a18f-7e5dab9e9a05"
        },{
          id: "9",
          name: "乡镇边界调整",
          pepor: "技术支持",
          url: "https://fxpc.mem.gov.cn/study/video/0308/9.mp4",
          img: "@/assets/images/activity/imgdd9.png",
          nr: `技术支持 国信司南(北京)地理信息技术有限公司，中级工程师`,
          pid: "032",
          zwzc: "",
          kscd: "3分钟",
          fjid: "14f1e55e-0b25-49c7-9720-449bfba7054e"
        },{
          id: "10",
          name: "审核上报",
          pepor: "技术支持",
          url: "https://fxpc.mem.gov.cn/study/video/0308/10.mp4",
          img: "@/assets/images/activity/imgdd10.png",
          nr: `技术支持 国信司南(北京)地理信息技术有限公司，中级工程师`,
          pid: "032",
          zwzc: "",
          kscd: "4分钟",
          fjid: "3a6ebbf6-a207-476f-a28b-0533630b4979"
        },]
      },
      {
        id: "04",
        date: "2021年03月",
        imgUrl: "@/assets/images/home/home_list_img.png",
        titile: "风险普查直播答疑专题",
        zzdw: "国务院普查办",
        kcsl: "8讲",
        hdlx: "线上",
        pxdx: "全国省市县普查办、行业部门和技术支撑单位相关人员",
        pxrs: "1000",
        kscd: "9小时49分钟",
        ts: "4",
        kssj: "2021-03-19",
        jssj: "2021-03-19",
        hdjj:
        "活动简介：随着第一次全国自然灾害综合风险普查工作的全面推行，为帮助相关普查人员快速掌握系统软件操作流程，深入理解调查技术规范，国务院普查办组织相关技术单位进行直播答疑，解答供相关普查人员在工作中遇到的相关问题推进相关的普查工作。",
        kcList: [
          {
            id: "1",
            name: "风险普查直播答疑第01期：普查区划更新",
            pepor: "技术支持",
            url: "https://fxpc.mem.gov.cn/study/video/0319/1.mp4",
            img: "@/assets/images/activity/imgdd1.png",
            nr: `吴灿，张丽娜 国务院普查办`,
            pid: "031",
            zwzc: "",
            kscd: "65分钟",
            fjid: "5537528f-1053-4600-a9be-0c47e6b685d4"
          },
          {
            id: "2",
            name: "风险普查直播答疑第02期：普查进展及统一入口登录",
            pepor: "技术支持",
            url: "https://fxpc.mem.gov.cn/study/video/0319/2.mp4",
            img: "@/assets/images/activity/imgdd1.png",
            nr: `周洪建，宋茜茜  国务院普查办`,
            pid: "031",
            zwzc: "",
            kscd: "107分钟",
            fjid: "074e7344-01d4-478d-ade0-7e08318b98a9"
          },
          {
            id: "3",
            name: "风险普查直播答疑第03期：普查区划更新",
            pepor: "技术支持",
            url: "https://fxpc.mem.gov.cn/study/video/0406/3.mp4",
            img: "@/assets/images/activity/imgdd1.png",
            nr: `张丽娜、袁家红、王淼鑫 国务院普查办`,
            pid: "031",
            zwzc: "",
            kscd: "86分钟",
            fjid: "dd49f748-fa0a-4017-a389-155dd14c3a64"
          },
          {
            id: "4",
            name: "风险普查答疑第04期：调度管理系统",
            pepor: "技术支持",
            url: "https://fxpc.mem.gov.cn/study/video/0416/1.mp4",
            img: "@/assets/images/activity/imgdd1.png",
            nr: `国务院普查办调查组组长王志强，国务院普查办综合组副组长潘东华`,
            pid: "031",
            zwzc: "",
            kscd: "100分钟",
            fjid: ""
          },
          {
            id: "5",
            name: "风险普查直播答疑第05期：数据汇交系统介绍",
            pepor: "技术支持",
            url: "https://fxpc.mem.gov.cn/study/video/0422/1.mp4",
            img: "@/assets/images/activity/imgdd1.png",
            nr: `赵飞，鲍浩 国务院普查办`,
            pid: "031",
            zwzc: "",
            kscd: "61分钟",
            fjid: "8514c280-a419-11eb-a705-75aee9d9446e"
          },
          {
            id: "6",
            name: "风险普查直播答疑第06期：数据汇交子系统介绍",
            pepor: "技术支持",
            url: "https://fxpc.mem.gov.cn/study/video/0514/1.mp4",
            img: "@/assets/images/activity/imgdd1.png",
            nr: `鲍浩、国务院普查办`,
            pid: "031",
            zwzc: "",
            kscd: "63分钟",
            fjid: "b15494a0-b491-11eb-8f2f-ff2e7122e753"
          },
          {
            id: "7",
            name: "风险普查直播答疑第07期：调度管理与应急质检系统培训",
            pepor: "技术支持",
            url: "https://fxpc.mem.gov.cn/study/video/0528/1.mp4",
            img: "@/assets/images/activity/imgdd1.png",
            nr: `吴灿、王淼鑫、张蕊、张丽娜、国务院普查办软件组`,
            pid: "031",
            zwzc: "",
            kscd: "77分钟",
            fjid: "081546a0-bf90-11eb-96c2-1f36d900a3e9"
          },
          {
            id: "8",
            name: "风险普查直播答疑第08期：数据汇交子系统介绍",
            pepor: "技术支持",
            url: "https://fxpc.mem.gov.cn/study/video/0611/1.mp4",
            img: "@/assets/images/activity/imgdd1.png",
            nr: `鲍浩、国务院普查办`,
            pid: "031",
            zwzc: "",
            kscd: "30分钟",
            fjid: "1bd67d60-ca78-11eb-b90e-d14d9ba18c73"
          },
        ]
        },
        {
          id: "05",
          date: "2021年06月",
          imgUrl: "@/assets/images/home/home_list_img.png",
          titile: "技术专题培训班（河南郑州）",
          zzdw: "国务院普查办",
          kcsl: "26讲",
          hdlx: "线下",
          pxdx: "省级普查办技术组组长和业务骨干",
          pxrs: "188",
          kscd: "13小时34分钟",
          ts: "4",
          kssj: "2021-06-16",
          jssj: "2021-06-16",
          hdjj:
          "活动简介：由国务院普查办主办的第一次全国自然灾害综合风险普查业务技术专题培训班于2021年6月16日至18日在河南郑州举行，培训内容含普查技术总体方案专题、评估与区划专题、调查与质检专题、数据管理与软件建设专题以及行业部门关于普查组织实施、调查及评估专题。",
          kcList: [
            {
              id: "1",
              name: "数据与成果管理办法",
              pepor: "刘龙飞",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0616/am/1.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `刘龙飞 国务院普查办数据与成果应用组副组长`,
              pid: "031",
              zwzc: "",
              kscd: "53分钟",
              fjid: "98965fd0-d7e0-11eb-802a-f7d50818c881"
            },
            {
              id: "2",
              name: "数据横向汇交及软件操作",
              pepor: "张效亮",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0616/am/2.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `张效亮 国务院普查办数据与成果应用组副组长`,
              pid: "031",
              zwzc: "",
              kscd: "35分钟",
              fjid: "cb366d40-d7e0-11eb-bda4-cd7e433b105f"
            },
            {
              id: "3",
              name: "普查软件省级部署方案",
              pepor: "张学华",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0616/am/3.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `张学华 国务院普查办软件系统与数据库组副组长`,
              pid: "031",
              zwzc: "",
              kscd: "109分钟",
              fjid: "e592c760-d7e0-11eb-bd40-5b7a389f209a"
            },
            {
              id: "4",
              name: "普查技术体系解读",
              pepor: "史培军",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0616/am/4.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `史培军 国务院普查办技术组组长`,
              pid: "031",
              zwzc: "",
              kscd: "",
              fjid: "21efcff0-d7e1-11eb-802a-f7d50818c881"
            },
            {
              id: "5",
              name: "综合减灾能力评估",
              pepor: "徐  伟",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0616/pm/1.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `徐  伟 国务院普查办评估组副组长`,
              pid: "031",
              zwzc: "",
              kscd: "40分钟",
              fjid: "9210f390-d7e1-11eb-84fc-071c7fd3ed29"
            },
            {
              id: "6",
              name: "自然灾害重点隐患综合评估",
              pepor: "方伟华",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0616/pm/2.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `方伟华 国务院普查办评估组副组长`,
              pid: "031",
              zwzc: "",
              kscd: "47分钟",
              fjid: "c56583f0-d7e1-11eb-84fc-071c7fd3ed29"
            },
            {
              id: "7",
              name: "自然灾害综合风险评估",
              pepor: "杨赛霓",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0616/pm/3.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `杨赛霓 国务院普查办评估组副组长`,
              pid: "031",
              zwzc: "",
              kscd: "59分钟",
              fjid: "018a1760-d7e2-11eb-bda4-cd7e433b105f"
            },
            {
              id: "8",
              name: "综合风险区划与防治区划",
              pepor: "王  瑛",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0616/pm/4.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `王  瑛 国务院普查办评估组副组长`,
              pid: "031",
              zwzc: "",
              kscd: "41分钟",
              fjid: "18c20000-d7e2-11eb-802a-f7d50818c881"
            },
            {
              id: "9",
              name: "应急系统调查任务和标准规范",
              pepor: "王志强",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0617/am/1.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `王志强 国务院普查办调查组组长`,
              pid: "031",
              zwzc: "",
              kscd: "39分钟",
              fjid: "f62690d0-d7e4-11eb-84fc-071c7fd3ed29"
            },
            {
              id: "10",
              name: "应急系统质检核查方案",
              pepor: "王  曦",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0617/am/2.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `王  曦 国务院普查办调查组副组长`,
              pid: "031",
              zwzc: "",
              kscd: "40分钟",
              fjid: "2762c880-d7e5-11eb-bd40-5b7a389f209a"
            },
            {
              id: "11",
              name: "应急系统调查软件操作",
              pepor: "刘蓓蓓",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0617/am/3.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `刘蓓蓓 国务院普查办调查组 `,
              pid: "031",
              zwzc: "",
              kscd: "",
              fjid: "4d01d360-d7e5-11eb-bda4-cd7e433b105f"
            },
            {
              id: "12",
              name: "历史灾害调查与评估任务",
              pepor: "汪  洋",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0617/am/4.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `汪  洋 国务院普查办调查组`,
              pid: "031",
              zwzc: "",
              kscd: "41分钟",
              fjid: "ca03c760-d7e5-11eb-bd40-5b7a389f209a"
            },
            {
              id: "13",
              name: "地方现场调查做法和经验分享——以巴林右旗应急调查为例",
              pepor: "李志鹏",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0617/am/5.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `李志鹏 内蒙古自治区赤峰市应急局综合减灾与救灾科科长`,
              pid: "031",
              zwzc: "",
              kscd: "47分钟",
              fjid: "ff6e6680-d7e5-11eb-bda4-cd7e433b105f"
            },
            {
              id: "14",
              name: "地质灾害普查组织实施、调查及评估工作",
              pepor: "佟彬",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0617/pm/1.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `佟彬 中国地质环境监测院`,
              pid: "031",
              zwzc: "",
              kscd: "29分钟",
              fjid: "8553cc40-d7eb-11eb-802a-f7d50818c881"
            },
            {
              id: "15",
              name: "海洋灾害普查组织实施、调查及评估工作",
              pepor: "张尧",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0617/pm/2.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `张尧 自然资源部海洋减灾中心`,
              pid: "031",
              zwzc: "",
              kscd: "11分钟",
              fjid: "1321c6d0-d7e7-11eb-bd40-5b7a389f209a"
            },
            {
              id: "16",
              name: "水旱灾害普查组织实施、调查及评估工作",
              pepor: "孙东亚",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0617/pm/3.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `孙东亚 水利部减灾中心`,
              pid: "031",
              zwzc: "",
              kscd: "33分钟",
              fjid: "2d51e0d0-d7e7-11eb-bda4-cd7e433b105f"
            },
            {
              id: "17",
              name: "气象灾害普查组织实施、调查及评估工作",
              pepor: "王国复",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0617/pm/4.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `王国复 国家气候中心`,
              pid: "031",
              zwzc: "",
              kscd: "34分钟",
              fjid: "42f2fcd0-d7e7-11eb-84fc-071c7fd3ed29"
            },
            {
              id: "18",
              name: "地震灾害普查组织实施、调查及评估工作",
              pepor: "中国地震灾害防御中心",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0617/pm/5.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `中国地震灾害防御中心`,
              pid: "031",
              zwzc: "",
              kscd: "30分钟",
              fjid: "58c69a80-d7e7-11eb-bda4-cd7e433b105f"
            },
            {
              id: "19",
              name: "森林和草原火灾普查组织实施、调查及评估工作",
              pepor: "杨雪清",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0618/pm/1.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `杨雪清 林草局调查规划设计院`,
              pid: "031",
              zwzc: "",
              kscd: "34分钟",
              fjid: "5f1ad5e0-d7ec-11eb-802a-f7d50818c881"
            },
            {
              id: "20",
              name: "民用核设施普查组织实施及调查工作",
              pepor: "李亮",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0618/pm/1.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `李亮 生态环境部核与辐射安全中心`,
              pid: "031",
              zwzc: "",
              kscd: "29分钟",
              fjid: "96fae1d0-d7ec-11eb-bda4-cd7e433b105f"
            },
            {
              id: "21",
              name: "房屋建筑和市政设施普查组织实施及调查工作",
              pepor: "张巍",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0618/pm/3.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `张巍 住建部工程质量安全监管司`,
              pid: "031",
              zwzc: "",
              kscd: "30分钟",
              fjid: "aa922410-d7ec-11eb-bda4-cd7e433b105f"
            },
            {
              id: "21",
              name: "公路和水路普查组织实施及调查工作",
              pepor: "杨峰",
              url: "https://fxpc.mem.gov.cn/study/video/hnzz/0618/pm/4.mp4",
              img: "@/assets/images/activity/imgdd1.png",
              nr: `杨峰 交通运输部路网监测与应急处置中心`,
              pid: "031",
              zwzc: "",
              kscd: "33分钟",
              fjid: "bccf7ba0-d7ec-11eb-bda4-cd7e433b105f"
            },
          ]
          },
          {
            id: "06",
            date: "2021年06月",
            imgUrl: "@/assets/images/home/home_list_img.png",
            titile: "管理专题培训班（河南郑州）",
            zzdw: "国务院普查办",
            kcsl: "4讲",
            hdlx: "线下",
            pxdx: "省级普查办主任和处级干部",
            pxrs: "188",
            kscd: "3小时9分钟",
            ts: "4",
            kssj: "2021-06-17",
            jssj: "2021-06-19",
            hdjj:
            "活动简介：由国务院普查办主办的第一次全国自然灾害综合风险普查业务管理专题培训班于2021年6月17日至19日在河南郑州举行，培训内容含普查总体方案专题、管理专题等。",
            kcList: [
              {
                id: "1",
                name: "普查组织管理",
                pepor: "袁  艺",
                url: "https://fxpc.mem.gov.cn/study/video/hnzz/0618/am/1.mp4",
                img: "@/assets/images/activity/imgdd1.png",
                nr: `袁  艺 国务院普查办副主任`,
                pid: "031",
                zwzc: "",
                kscd: "64分钟",
                fjid: "9fbebdd0-d0c3-11eb-81d8-253a0099d800"
              },
              {
                id: "2",
                name: "普查技术体系及评估与区划体系",
                pepor: "汪  明",
                url: "https://fxpc.mem.gov.cn/study/video/hnzz/0618/am/2.mp4",
                img: "@/assets/images/activity/imgdd1.png",
                nr: `汪  明 国务院普查办技术组常务副组长`,
                pid: "031",
                zwzc: "",
                kscd: "61分钟",
                fjid: "540b3480-d0c4-11eb-bd40-5b7a389f209a"
              },
              {
                id: "3",
                name: "数据汇交与管理",
                pepor: "赵  飞",
                url: "https://fxpc.mem.gov.cn/study/video/hnzz/0618/am/3.mp4",
                img: "@/assets/images/activity/imgdd1.png",
                nr: `赵  飞 国务院普查办数据与成果应用组组长`,
                pid: "031",
                zwzc: "",
                kscd: "30分钟",
                fjid: "d0f61e10-d0c4-11eb-81d8-253a0099d800"
              },
              {
                id: "3",
                name: "普查软件系统总体设计",
                pepor: "廖永丰",
                url: "https://fxpc.mem.gov.cn/study/video/hnzz/0618/am/4.mp4",
                img: "@/assets/images/activity/imgdd1.png",
                nr: `廖永丰 国务院普查办软件系统与数据库组组长`,
                pid: "031",
                zwzc: "",
                kscd: "34分钟",
                fjid: "1799eb30-d0c5-11eb-bd23-33e582353f3b"
              },
            ]
            },
        
  ],
}
