export const mime = { 
    ".doc":"application/msword" ,
    ".docx":"application/vnd.openxmlformats-officedocument.wordprocessingml.document" ,
    ".xls":"application/vnd.ms-excel" ,
    ".xlsx":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" ,
    ".ppt":"application/vnd.ms-powerpoint" ,
  ".pptx":"application/vnd.openxmlformats-officedocument.presentationml.presentation" ,
  ".pdf":"application/pdf" ,
  ".jpeg":"image/jpeg" ,
  ".jpg":"image/jpeg" ,
  ".png":"image/png" ,
  ".bmp":"image/bmp" ,
  ".mp4":"video/mp4" ,
  ".avi":"video/x-msvideo" ,
  ".mov":"video/quicktime" ,
  ".rmvb":"audio/x-pn-realaudio" ,
  ".rm":"audio/x-pn-realaudio" ,
  ".flv":"flv-application/octet-stream" ,
  ".3gp":"video/3gpp" ,
  ".rar":"application/octet-stream" ,
  ".zip":"application/zip",
  ".DOC":"application/msword" ,
    ".DOCX":"application/vnd.openxmlformats-officedocument.wordprocessingml.document" ,
    ".XLS":"application/vnd.ms-excel" ,
    ".XLSX":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" ,
    ".PPT":"application/vnd.ms-powerpoint" ,
  ".PPTX":"application/vnd.openxmlformats-officedocument.presentationml.presentation" ,
  ".PDF":"application/pdf" ,
  ".JPEG":"image/jpeg" ,
  ".JPG":"image/jpeg" ,
  ".PNG":"image/png" ,
  ".BMP":"image/bmp" ,
  ".MP4":"video/mp4" ,
  ".3GP":"video/3gpp" ,
  ".webm":"video/webm",
  ".ogg":"video/ogg" ,
  ".RMVB":"audio/x-pn-realaudio" ,
  ".RM":"audio/x-pn-realaudio" ,
  ".FLV":"flv-application/octet-stream" ,
  ".RAR":"application/octet-stream" ,
  ".ZIP":"application/zip"
}
