/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATree: typeof import('ant-design-vue/es')['Tree']
    CaretDownFilled: typeof import('@ant-design/icons-vue')['CaretDownFilled']
    Layout: typeof import('./components/layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    UploadFilled: typeof import('@ant-design/icons-vue')['UploadFilled']
    WorkDynamics: typeof import('./components/layout/work-dynamics/index.vue')['default']
  }
}
